### ISSUE TITLE
Feature: modulo function

### ISSUE THREAD

**Issue by vektor8891** [maxinteger/pocket-lisp-stdlib#7]
implement modulo function

**Comment by maxinteger** [comment]
@vektor8891 Is this still relevant?

**Comment by vektor8891** [comment]
@maxinteger No, I've [added](https://github.com/maxinteger/pocket-lisp-stdlib/blob/61d48aa6e39cee5d726714117c4412137fb12367/src/data/number/numberFn.ts#L85) it in #10
